/* tools/build-levels.js — builds levels.js, the frozen level packs.
 *
 * Run from the project root:  node tools/build-levels.js
 *
 * For every grid size and tier k (1 Doodle .. 4 Final Exam) it carves candidate
 * puzzles allowed to rely only on techniques <= k, keeps those that genuinely
 * NEED tier k (so each section really teaches its technique), drops
 * duplicates, sorts by clue count (most clues = easiest first) and takes 10
 * evenly spaced, so each section ramps from easier to harder.
 *
 * Fully deterministic: seeds come from fixed strings, ties sort by clue string.
 * Running it twice produces a byte-identical levels.js. The game never
 * generates levels itself; re-running this script is the ONLY way levels
 * change, so do it deliberately (it would re-shuffle players' stars).
 */
const fs = require("fs");
const path = require("path");
const B = require("../board.js");
const S = require("../solver.js");
const G = require("../generator.js");
const P = require("../progress.js");

const SIZES = [6, 8, 10, 12, 14];
const POOL = 25;            // accepted candidates collected per size/tier
const MAX_CANDIDATES = 600; // give up (loudly) after this many tries

function clueCount(str) {
  let n = 0;
  for (const ch of str.slice(str.indexOf(":") + 1)) if (ch !== ".") n++;
  return n;
}

function buildTier(size, k) {
  const pool = new Set();
  let tried = 0;
  for (let c = 0; c < MAX_CANDIDATES && pool.size < POOL; c++) {
    tried++;
    const rand = G.mulberry32(G.hashString("level-" + size + "-tier-" + k + "-cand-" + c));
    let sol;
    try { sol = G.buildCompleteGrid(size, rand); }
    catch (e) { if (e === G.BUILD_BUDGET) continue; throw e; }
    const clues = G.carvePuzzle(sol, size, rand, { maxTier: k });
    const r = S.solve(clues, size, { maxTrialDepth: 0 });
    if (!r.solved || r.maxTier !== k) continue;
    pool.add(B.gridToString(clues, size));
  }
  if (pool.size < P.LEVELS_PER_TIER) {
    throw new Error("build-levels: only " + pool.size + " puzzles for " + size + "x" + size +
      " tier " + k + " after " + tried + " candidates");
  }
  const sorted = [...pool].sort((a, b) => clueCount(b) - clueCount(a) || (a < b ? -1 : a > b ? 1 : 0));
  const picks = [];
  for (let j = 0; j < P.LEVELS_PER_TIER; j++) {
    picks.push(sorted[Math.round(j * (sorted.length - 1) / (P.LEVELS_PER_TIER - 1))]);
  }
  console.log("  " + size + "x" + size + " " + P.TIER_NAMES[k - 1] + ": " + pool.size + " candidates from " +
    tried + " tries, clues " + clueCount(picks[0]) + " -> " + clueCount(picks[picks.length - 1]));
  return picks;
}

const lines = [
  "/* levels.js — GENERATED by tools/build-levels.js. Do not edit by hand.",
  " *",
  " * 40 fixed levels per grid size, as clue strings (gridToString). Levels",
  " * 1-10 Doodle, 11-20 Homework, 21-30 Pop Quiz, 31-40 Final Exam (see",
  " * progress.js). The solution is recomputed by the solver when a level opens.",
  " */",
  "const LEVELS_VERSION = 1;",
  "const LEVELS = {",
];
for (const size of SIZES) {
  const levels = [];
  for (let k = 1; k <= 4; k++) levels.push(...buildTier(size, k));
  lines.push("  " + size + ": [");
  for (const str of levels) lines.push('    "' + str + '",');
  lines.push("  ],");
}
lines.push("};");
lines.push("");
lines.push('if (typeof module !== "undefined" && module.exports) {');
lines.push("  module.exports = { LEVELS, LEVELS_VERSION };");
lines.push("}");
lines.push("");

const out = path.join(__dirname, "..", "levels.js");
fs.writeFileSync(out, lines.join("\n"));
console.log("wrote " + out + " (" + fs.statSync(out).size + " bytes)");
