/* tools/build-levels.js — builds levels.js, the frozen level packs.
 *
 * Run from the project root:  node tools/build-levels.js
 *
 * v2: 200 levels per grid size, four independent sections of 50 (Doodle,
 * Homework, Pop Quiz, Final Exam). For every size and tier k it carves
 * candidate puzzles allowed to rely only on techniques <= k and keeps those
 * that genuinely NEED tier k (so each section really teaches its technique).
 *
 * Every board from the first release (tools/levels-v1.js, 10 per section) is
 * kept: each section = its 10 v1 boards + 40 new ones taken evenly spaced from
 * the new candidates, all sorted by clue count (most clues = easiest first).
 * LEVELS_V1_MAP records where each v1 board landed, so players' v1 stars move
 * with their boards (progress.js migrateProgressV1).
 *
 * Fully deterministic: seeds come from fixed strings, ties sort by clue string.
 * Running it twice produces a byte-identical levels.js. The game never
 * generates levels itself; re-running this script is the ONLY way levels
 * change, so do it deliberately — and bump LEVELS_VERSION with a migration if
 * existing boards ever move again.
 */
const fs = require("fs");
const path = require("path");
const B = require("../board.js");
const S = require("../solver.js");
const G = require("../generator.js");
const P = require("../progress.js");
const V1 = require("./levels-v1.js").LEVELS;

const SIZES = [6, 8, 10, 12, 14];
const V1_PER_TIER = 10;
const NEW_PER_TIER = P.LEVELS_PER_TIER - V1_PER_TIER; // 40
const NEW_POOL = 100;        // new (non-v1) candidates collected per size/tier
const MAX_CANDIDATES = 4000; // give up (loudly) after this many tries

function clueCount(str) {
  let n = 0;
  for (const ch of str.slice(str.indexOf(":") + 1)) if (ch !== ".") n++;
  return n;
}
const byEase = (a, b) => clueCount(b) - clueCount(a) || (a < b ? -1 : a > b ? 1 : 0);

function buildTier(size, k) {
  const v1 = V1[size].slice((k - 1) * V1_PER_TIER, k * V1_PER_TIER);
  const v1Set = new Set(v1);
  const pool = new Set();
  let tried = 0;
  for (let c = 0; c < MAX_CANDIDATES && pool.size < NEW_POOL; c++) {
    tried++;
    const rand = G.mulberry32(G.hashString("level-" + size + "-tier-" + k + "-cand-" + c));
    let sol;
    try { sol = G.buildCompleteGrid(size, rand); }
    catch (e) { if (e === G.BUILD_BUDGET) continue; throw e; }
    const clues = G.carvePuzzle(sol, size, rand, { maxTier: k });
    const r = S.solve(clues, size, { maxTrialDepth: 0 });
    if (!r.solved || r.maxTier !== k) continue;
    const str = B.gridToString(clues, size);
    if (!v1Set.has(str)) pool.add(str);
  }
  if (pool.size < NEW_PER_TIER) {
    throw new Error("build-levels: only " + pool.size + " new puzzles for " + size + "x" + size +
      " tier " + k + " after " + tried + " candidates");
  }
  const sorted = [...pool].sort(byEase);
  const picks = [];
  for (let j = 0; j < NEW_PER_TIER; j++) {
    picks.push(sorted[Math.round(j * (sorted.length - 1) / (NEW_PER_TIER - 1))]);
  }
  const section = v1.concat(picks).sort(byEase);
  console.log("  " + size + "x" + size + " " + P.TIER_NAMES[k - 1] + ": " + pool.size + " new candidates from " +
    tried + " tries, clues " + clueCount(section[0]) + " -> " + clueCount(section[section.length - 1]));
  return section;
}

const lines = [
  "/* levels.js — GENERATED by tools/build-levels.js. Do not edit by hand.",
  " *",
  " * 200 fixed levels per grid size, as clue strings (gridToString). Levels",
  " * 1-50 Doodle, 51-100 Homework, 101-150 Pop Quiz, 151-200 Final Exam (see",
  " * progress.js). The solution is recomputed by the solver when a level opens.",
  " * LEVELS_V1_MAP[size][k] = the level number of v1 level k+1 (same board).",
  " */",
  "const LEVELS_VERSION = 2;",
  "const LEVELS = {",
];
const maps = {};
for (const size of SIZES) {
  const levels = [];
  for (let k = 1; k <= 4; k++) levels.push(...buildTier(size, k));
  maps[size] = V1[size].map((str) => levels.indexOf(str) + 1);
  if (maps[size].some((n) => n === 0)) throw new Error("build-levels: lost a v1 board at " + size + "x" + size);
  lines.push("  " + size + ": [");
  for (const str of levels) lines.push('    "' + str + '",');
  lines.push("  ],");
}
lines.push("};");
lines.push("const LEVELS_V1_MAP = {");
for (const size of SIZES) lines.push("  " + size + ": [" + maps[size].join(", ") + "],");
lines.push("};");
lines.push("");
lines.push('if (typeof module !== "undefined" && module.exports) {');
lines.push("  module.exports = { LEVELS, LEVELS_VERSION, LEVELS_V1_MAP };");
lines.push("}");
lines.push("");

const out = path.join(__dirname, "..", "levels.js");
fs.writeFileSync(out, lines.join("\n"));
console.log("wrote " + out + " (" + fs.statSync(out).size + " bytes)");
